services:
  frontend:
    image: ghcr.io/emmauopeople/1community-app-frontend:${FRONTEND_IMAGE_TAG}
    container_name: cameroonskills-frontend
    restart: unless-stopped
    expose:
      - "5173"

  backend:
    image: ghcr.io/emmauopeople/1community-app-backend:${BACKEND_IMAGE_TAG}
    container_name: cameroonskills-backend
    restart: unless-stopped
    env_file:
      - .env
      - .env.deploy
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: cameroonskills-nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot
    container_name: cameroonskills-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
      while :; do
      certbot renew --webroot -w /var/www/certbot --quiet;
      sleep 12h & wait $${!};
      done"
  # ============================
  # Monitoring Stack
  # ============================

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    pid: host
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

                                            